Feature/user permission by project
jschuhmann47/projectMap-Backend pull request #10
Opened 2024-08-11 22:44 UTC by DiegoAnazonian

2024-08-12 13:10 UTC, jschuhmann47 requested changes

2024-08-12 13:10 UTC, jschuhmann47 commented on database-schema.md
> +  "titulo": "tittle",
si ponemos todo en ingles esto deberíamos cambiarlo (title, description etc)

2024-08-12 13:10 UTC, jschuhmann47 commented on database-schema.md
> +      "email": "email1@gmail.com"
acá sería una lista de ids entonces

2024-08-12 13:10 UTC, jschuhmann47 commented on database-schema.md
> +      "userEmail": "user3@gmail.com",
id en vez de mail

2024-08-12 13:10 UTC, jschuhmann47 commented on src/project/project.controller.ts
> +        @Body() projectDTO: UpdateCoordinatorRolesDro
```suggestion
        @Body() projectDTO: UpdateCoordinatorRolesDto
```

2024-08-12 13:10 UTC, jschuhmann47 commented on src/project/project.controller.ts
> +        const project = await this.projectService.getOne(projectId)
habría que chequear que este método getOne te popule los datos (creo que lo hacía en mi otro PR)

2024-08-12 13:10 UTC, jschuhmann47 commented on src/project/project.controller.ts
> +            (participant) => participant.email == userEmail
coordinator mejor para el parámetro

2024-08-12 13:10 UTC, jschuhmann47 commented on src/project/project.controller.ts
> +            (participant) => participant.userEmail == userEmail
si usamos id sería participant.user.email (y que esté populado)

2024-08-12 13:10 UTC, jschuhmann47 commented on src/project/project.controller.ts
> +        if (userStagePermission && userStagePermission.permission != 'write') {
este chequeo creo que debería ir al momento de editar algo del proyecto, no en un endpoint en sí. Por ejemplo el usuario intenta crear un foda -> no le deja porque tiene read

2024-08-12 13:10 UTC, jschuhmann47 commented on src/project/project.service.ts
>      async updateParticipanRole(
```suggestion
    async updateParticipantRole(
```

2024-08-12 13:10 UTC, jschuhmann47 commented on src/project/stage.schema.ts
>      _id: mongoose.Types.ObjectId
no sería string? o usamos los de mongo? digo porque en el json de ejemplo le pusimos st1 etc

2024-08-16 12:48 UTC, DiegoAnazonian commented on database-schema.md
> +  "titulo": "tittle",
Entiendo que habiamos dicho de poner en español para que funcione incluso el guardado de titulo, color desde el front.. eso cambio ?

2024-08-16 12:50 UTC, DiegoAnazonian commented on database-schema.md
> +      "email": "email1@gmail.com"
Si cambiamos por ids entonces si, cambiemos esta docu tambien

2024-08-16 12:55 UTC, DiegoAnazonian commented on src/project/project.controller.ts
> +        const project = await this.projectService.getOne(projectId)
Popular con que informacion ? Le comente el "owner" dentro del metodo *getOne* que es algo que ya no se usa. El metodo getOne trae todo el proyecto y la funcion corre ok.

2024-08-16 12:57 UTC, DiegoAnazonian commented on src/project/project.controller.ts
> +        if (userStagePermission && userStagePermission.permission != 'write') {
Este endpoint se creo para esa validacion, es la que un usuario quiere intentar ingresar a un stage dentro de un proyecto y este user no tiene permiso. Es el unico medio de validacion por backend sobre eso.
Ticket -> https://trello.com/c/lo7FIKbH/62-deshabilitar-creacion-y-edicion-en-las-etapas-en-las-que-tengo-solo-lectura-devolver-403-b

2024-08-17 00:02 UTC, jschuhmann47 commented on database-schema.md
> +  "titulo": "tittle",
queda asi

2024-08-17 00:03 UTC, jschuhmann47 commented on src/project/project.controller.ts
> +        const project = await this.projectService.getOne(projectId)
con la de los participantes y coordinadores, sino va a iterar con la lista vacía

2024-08-17 00:05 UTC, jschuhmann47 commented on src/project/project.controller.ts
> +        if (userStagePermission && userStagePermission.permission != 'write') {
pero habría que validarlo, entiendo, al entrar a cada herramienta, sino podes entrar desde el front a mano a por ej project/foda/1 y te salteas este check

2024-08-17 21:55 UTC, DiegoAnazonian commented on src/project/project.controller.ts
> +        const project = await this.projectService.getOne(projectId)
ahi lo probe y funciona ok lo de popular

2024-08-17 21:56 UTC, DiegoAnazonian commented on src/project/project.controller.ts
> +        if (userStagePermission && userStagePermission.permission != 'write') {
Exacto esa es la idea. El ticket que tome era el endpoint del backend nomas, faltaria adaptarlo al front para que cada vez que un user hace click en la herramienta que quiere editar se verifique el endpoint

2024-08-21 01:58 UTC, jschuhmann47 requested changes

2024-08-21 01:58 UTC, jschuhmann47 commented on database-schema.md
> +      "email": "email1@gmail.com"
TODO cambiar

2024-08-21 01:58 UTC, jschuhmann47 commented on database-schema.md
> +      "userEmail": "user3@gmail.com",
falta este cambio

2024-08-21 01:58 UTC, jschuhmann47 commented on database-schema.md
> +          "permision": "read" // read | write | view
es edit, view y hide al final

2024-08-21 01:58 UTC, jschuhmann47 commented on database-schema.md
> +          "id": "st2",
los ids fijate en el codigo hay un enum

2024-08-21 01:58 UTC, jschuhmann47 commented on database-schema.md
> +  "projectsId": [] // se usa ?
```suggestion
```

2024-08-21 01:58 UTC, jschuhmann47 commented on src/middleware/project.middleware.ts
> +      console.log(`El usuario: ${email} no tiene permisos para editar la herramietna ${tool} bajo el stage: ${stage}`)
```suggestion
      console.log(`El usuario: ${email} no tiene permisos para editar la herramienta ${tool} bajo el stage: ${stage}`)
```

2024-08-21 01:58 UTC, jschuhmann47 commented on src/project/participant.schema.ts
> +    @Prop()
Creo que lo de object es para parsearlo a la hora de traerlo de mongo, si probaste que ande sin eso lo sacamos pero sino lo dejaría

2024-08-21 01:58 UTC, jschuhmann47 commented on src/project/project.controller.ts
> +    @Get(':id/users/:userEmail/roles')
esto borrar

2024-08-21 01:58 UTC, jschuhmann47 commented on src/project/project.controller.ts
> +    @Get(':id/user/:userEmail/stage/:stageId/edit')
borrar

2024-08-21 01:58 UTC, jschuhmann47 commented on src/app.module.ts
> +                path: 'foda',
pregunta, esto lo usa en todas las rutas ej foda/edit, foda/... ? o solo en /foda y nada más?

2024-08-27 13:59 UTC, DiegoAnazonian commented on src/app.module.ts
> +                path: 'foda',
solo en "foda" y nada mas. Si tenes /foda/algo, no aplica

2024-08-27 18:08 UTC, jschuhmann47 commented on src/app.module.ts
> +                path: 'foda',
creo que debería aplicar, porque si por ej querés editar el foda 1234, la ruta va a ser algo como PUT foda/1234 y ahi le va a dejar al usuario, no se si se puede meter expresion regular o algo, estilo foda/**

2024-08-27 18:08 UTC, jschuhmann47 commented on src/middleware/project.middleware.ts
> +            console.log(
sacar el console log

2024-08-27 18:32 UTC, DiegoAnazonian commented on src/app.module.ts
> +                path: 'foda',
La ruta actual es /Foda y la info se envia en el body.. asi es para todas las etapas actuales.

2024-08-27 20:41 UTC, jschuhmann47 approved these changes

2024-08-27 20:43 UTC, merged