Feature/define okr model
jschuhmann47/projectMap-Backend pull request #15
Opened 2024-08-25 14:09 UTC by jschuhmann47

2024-08-30 23:12 UTC, T-J-Antonio requested changes

2024-08-30 23:12 UTC, T-J-Antonio commented on src/herramientas/okr/okr.schema.ts
> +    TRIMESTER,
quarter y trimester es lo mismo

2024-08-31 00:57 UTC, jschuhmann47 commented on src/herramientas/okr/okr.schema.ts
> +    TRIMESTER,
plot twist masivo

2024-09-01 15:05 UTC, T-J-Antonio requested changes

2024-09-01 15:05 UTC, T-J-Antonio commented on src/herramientas/okr/okr.schema.ts
> +    SIX_MONTHS = 120,
```suggestion
    SIX_MONTHS = 180,
```

2024-09-02 02:21 UTC, T-J-Antonio requested changes

2024-09-02 02:21 UTC, T-J-Antonio commented on src/herramientas/okr/okr.service.ts
>                      keyResult.priority = keyResultDto.priority
esto no deja editar la prioridad y setearla en low (porque vale 0 y es falsy)

2024-09-02 02:35 UTC, jschuhmann47 commented on src/herramientas/okr/okr.service.ts
>                      keyResult.priority = keyResultDto.priority
:a:

2024-09-04 00:45 UTC, T-J-Antonio approved these changes

2024-09-04 00:53 UTC, merged