feat: let print progress when goal es less than baseline
jschuhmann47/projectMap-Backend pull request #44
Opened 2024-10-20 02:41 UTC by DiegoAnazonian

Aceptar baseline mayor a goal para un kr

2024-10-20 14:13 UTC, jschuhmann47 requested changes

2024-10-20 14:13 UTC, jschuhmann47 commented on src/herramientas/okr/okr.schema.ts
> +    value: number | null
Por qué nulleable?

2024-10-20 14:13 UTC, jschuhmann47 commented on src/herramientas/okr/okr.schema.ts
> +    let lastValue
Tipo number

2024-10-20 14:13 UTC, jschuhmann47 commented on src/herramientas/okr/okr.schema.ts
> +    const filtered: KeyStatus[] = keyStatus.filter((ks) => ks.value !== null)
Yo diría que en todo caso se inicialicen con baseline en vez de 0 y reusar la otra función

2024-10-20 23:19 UTC, DiegoAnazonian commented on src/herramientas/okr/okr.schema.ts
> +    value: number | null
lo hice nullable por que ahora podemos empezar el baseline en 100 por ejemplo y querer terminar en 0 el goal. De ser asi si ponemos todo en 0 por default no sabemos cuando el usuario ingreso 0 manualmente o cuando fue puesto por defecto por nosotros. Tambien sirve para una funciona que busca el primera valor distinto de cero, en este caso si tenemos todo cero no podria identificar si es realmente cero puesto por el usuario o no. Por eso null y en caso de encontrar 0 retornamos que se llego al goal

2024-10-20 23:22 UTC, DiegoAnazonian commented on src/herramientas/okr/okr.schema.ts
> +    const filtered: KeyStatus[] = keyStatus.filter((ks) => ks.value !== null)
si baseline es 100 por ejemplo, tendriamos 100 puesto en todos los keyStatus ? cuando al principio son todos vacios hasta que el usuario llena los valores.

2024-10-21 00:59 UTC, jschuhmann47 commented on src/herramientas/okr/okr.schema.ts
> +    const filtered: KeyStatus[] = keyStatus.filter((ks) => ks.value !== null)
Mm si creo que es medio bardo lo que dije jaja

2024-10-21 01:04 UTC, jschuhmann47 commented on src/herramientas/okr/okr.schema.ts
> +    value: number | null
Habría que ver tema front si se banca el null/cómo lo muestra

2024-10-21 01:04 UTC, jschuhmann47 commented on src/herramientas/okr/okr.schema.ts
> +    const filtered: KeyStatus[] = keyStatus.filter((ks) => ks.value !== null)
1) Habría que renombrar la función porque ya no es get last zero value, ahora es get first empty o algo así
2) Creo que ahora ambas podrían usar la misma función, total ya sea ascendente o descendente querés obtener el primer valor no nulo

2024-10-21 01:04 UTC, jschuhmann47 commented on src/herramientas/okr/okr.schema.ts
> +        lastValue = getLastNonZeroValue(this.keyStatus) as number
Creo que acá tmb habría que agregar lo de que si es null ponga la baseline

2024-10-28 01:31 UTC, DiegoAnazonian commented on src/herramientas/okr/okr.schema.ts
> +    const filtered: KeyStatus[] = keyStatus.filter((ks) => ks.value !== null)
Estoy de acuerdo, queria dejarlo separado asi se entendia bien el cambio, pero me parece bien 💪

2024-11-02 16:15 UTC, DiegoAnazonian commented on src/herramientas/okr/okr.schema.ts
> +        lastValue = getLastNonZeroValue(this.keyStatus) as number
En este punto no deberia ser null nunca por que la funcion retorna 0 como default

2024-11-03 13:32 UTC, jschuhmann47 requested changes

2024-11-03 13:32 UTC, jschuhmann47 commented on src/herramientas/okr/okr.schema.ts
> +    const filtered: KeyStatus[] = keyStatus.filter((ks) => ks.value !== null)
Falta esto

2024-11-03 23:24 UTC, DiegoAnazonian commented on src/herramientas/okr/okr.schema.ts
> +        lastValue = getLastNonZeroValue(this.keyStatus) as number
cambiado

2024-11-03 23:41 UTC, jschuhmann47 approved these changes

2024-11-04 23:22 UTC, merged